### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by thinh76** [thoughtbot/shoulda-matchers#1001]
With ruby 2.4.0 release, tests with shoulda matchers are giving the above warnings.

Here is the details referring to deprecating Fixnum
https://bugs.ruby-lang.org/issues/12005

**Comment by guialbuk** [comment]
Fixed by #1009

**Comment by leomao10** [comment]
Do we have a plan to release `v4.0` or backport it to `3.1.x`, looks like this issue still existed for the latest shoulda-matcher

**Comment by guialbuk** [comment]
Hi @leomao10 
You don't need to wait for a new release to have this issue fixed. You can use the master branch.

**Comment by chagar** [comment]
Are there not going to be any more releases? Use master from now on?

**Comment by guialbuk** [comment]
Hi @chagar 
 I recommend you to use the `master` branch. It is pretty stable.

**Comment by mcgoooo** [comment]
hi @guialbuk we are not very comfortable with the solution to use the master branch, is there any way a prerelease gem could be cut? looking at the milestone, there hasn't been any movement on them in a couple of years?

**Comment by guialbuk** [comment]
@mcgoooo Not sure what you mean about not having movement in a couple of years. 😕
Anyway, the 4.0 will be released very soon and It will be, besides documentation, exactly the current master branch.
Cheers!

**Comment by mcgoooo** [comment]
@guialbuk sorry, i was just looking at the milestone flag from the readme
https://github.com/thoughtbot/shoulda-matchers/milestone/13

Great work on the library btw!

**Comment by petergoldstein** [comment]
@guialbuk We just ran into this issue, and were wondering if there's an update on either:

1. `4.0` will be released as a gem
2. This fix could be backported to  the `3.1.x` branch and published as a new gem version.

Your last update (~8 months ago) said that 4.0 will be released 'very soon'.  Anything I can do to help?

**Comment by guialbuk** [comment]
Hi @petergoldstein 

1. 4.0 had significant code changes since the last year, and 4.0.0.rc1 is available: https://github.com/thoughtbot/shoulda-matchers/releases/tag/v4.0.0.rc1
2. Yes, and the 3.1.3 was released recently with this PR backported: https://github.com/thoughtbot/shoulda-matchers/releases/tag/v3.1.3

But my suggestion is to give a try to the `master` branch. That's the code with more features and support for edge cases. You should try it, as it runs smoothly in several big projects in production, and by using it people can contribute more towards 4.0.

Cheers

**Comment by petergoldstein** [comment]
Hi @guialbuk,

Thanks for the quick response.

So I'm using 3.1.3 and still seeing this error:

    .../gems/shoulda-matchers-3.1.3/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:551: warning: constant ::Fixnum is deprecated

Checking the code confirms that this issue exists in 3.1.3 - https://github.com/thoughtbot/shoulda-matchers/blob/3fea7992fd78f9365794de927f9f3589830a6947/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb#L551

Happy to provide a PR for the above issue against the 3.1.3 tag.

Unfortunately using `master` is not an option for us.  Once 4.0.0 is out, we'll be happy to try migrating.

Thanks.
