### ISSUE TITLE
Minitest: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.

### ISSUE THREAD

**Issue by brendon** [thoughtbot/shoulda-matchers#1284]
Using the recommended Minitest gem structure results in the `BigDecimal` warning because the fix wasn't back ported to the `2.x` branch.

Previously discussed in: #1166 @mcmire 

```ruby
group :test do
  gem 'shoulda', '~> 3.5'
  gem 'shoulda-matchers', '~> 2.0'
  gem 'rails-controller-testing'
end
```

**Comment by cristofer** [comment]
with Ruby 2.7.1 

```
NoMethodError: undefined method `new' for BigDecimal:Class
```

**Comment by mcmire** [comment]
Hey @brendon! Yup, just echoing @cristofer here. I'd like to avoid backporting if we can especially since shoulda-matchers 2.0 was released a pretty good while back. I would try upgrading to shoulda 4.0.0.rc2 in your project which I just released not too long ago and see if that helps clear things up. If that doesn't then we can pursue another route.

**Comment by brendon** [comment]
Hi @mcmire, thanks for the update. I tried that again but unfortunately still get the same error:

```
NoMethodError: undefined method `have_many' for FamilyMemberTest:Class
```

```
group :test do
  gem 'shoulda', '4.0.0.rc2'
  gem 'rails-controller-testing'
end
```

Looks like the helpers aren't being loaded in. Is there anything you'd like me to try?

**Comment by mcmire** [comment]
@brendon Yup, sorry, one last thing — in shoulda-matchers 4 (which this loads under the hood) we changed how you need to bring in the gem. So you'll want to throw this somewhere into your `test_helper`:

``` ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :minitest
    with.library :rails
  end
end
```

**Comment by brendon** [comment]
That worked perfectly! :D Thank you so much!
